# github.com/go-task/task

version: '3'

vars:
  BINARY_NAME: builder-clinet
  VERSION: v0.1.0
tasks:
  generate:
    env:
      GOOS: js
      GOARCH: wasm
    cmds:
      - go generate
  build:
    env:
      GOOS: js
      GOARCH: wasm
    cmds:
      - go build -o ./web/public/builder.wasm .
